### ISSUE TITLE
Error on nikic/PhpParser/Lexer.php

### ISSUE THREAD

**Issue by arno09** [sebastianbergmann/phpcov#113]
When I'm running phpcov 8.2.0 on a php 8.1 environment with phpUnit 9.5.10 I've got this error : 
```sh
phpcov 8.2.0 by Sebastian Bergmann.

Generating code coverage report in HTML format ... 
Warning: Undefined array key 336 in phar:///var/www/app/phpcov/nikic/PhpParser/Lexer.php on line 324

Fatal error: Uncaught TypeError: PhpParser\Lexer::getNextToken(): Return value must be of type int, null returned in phar:///var/www/app/phpcov/nikic/PhpParser/Lexer.php:364
```
For information, I get phpcov by doing `wget -q https://phar.phpunit.de/phpcov.phar -O phpcov`

**Comment by SamMousa** [comment]
It seems all that is needed to fix this is a new build.
This commit: https://github.com/sebastianbergmann/php-code-coverage/commit/347a87a7f8b2b78e87200d7de0058dd4ae05f76d adds the correct version of `php-parser` to the coverage library.

Phpcov requires `phpunit/php-code-coverage: ^9.2`, and the fix (dependency update) is included from `9.2.8` onwards.

Since this repo does not include a `composer.lock` file it is essentially saying that it'll work with dependency ranges as specified in the `composer.json` file; if that's the case then maybe it makes sense to automatically rebuild the PHAR archive and do a minor release every time one of the dependencies comes with a new release.
Assumptions:
  - Newer versions of dependencies are better
  - The contraints in `composer.json` are strict enough

**Comment by iamrekas** [comment]
Today is 2022-03-23 and still this issue are not fixed. its need just update dependencies as i understand. In readme phive way is recommended using this tool. Please fix it ASAP. Thank you.

**Comment by iamrekas** [comment]
Create PR for this. #117
For temporary published phar too in the fork.
