### ISSUE TITLE
Support for php-code-coverage ^9.1

### ISSUE THREAD

**Issue by marcingy** [sebastianbergmann/phpcov#98]
Currently phpcov can't be installed with phpunit 9.3 because of conflict with version of php-code-coverage needed.

**Comment by sebastianbergmann** [comment]
[Using Composer to install this tool is not recommended.](https://github.com/sebastianbergmann/phpcov#installation)

**Comment by sebastianbergmann** [comment]
This is not only a matter of "PHPCOV and PHPUnit 9.3 cannot be installed together with Composer".

PHPUnit 9.3 uses a new version of php-code-coverage. API changes in this new version of php-code-coverage require changes in PHPCOV. Changes introduced in PHPUnit's API for handling configuration file made in PHPUnit 9.0 (and since then) also need to be taken into account.

**Comment by sebastianbergmann** [comment]
I started to work on this in `master` but it might take some time until this is ready for release.

**Comment by sebastianbergmann** [comment]
PHPCOV 8.0.0 has been released with initial support for PHPUnit 9 / php-code-coverage 9.
